### Create a new Patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name": "Shreeram_billing",
  "email": "shreeram_billing@gmail.com",
  "address": "street 124",
  "dateOfBirth": "1990-08-08",
  "registeredDate": "1991-08-08"
}

###